### ISSUE TITLE
Please release 1.0.1-SNAPSHOT to maven

### ISSUE THREAD

**Issue by fbis251** [karan/jReddit#102]
Any IDE that uses maven makes it extremely easy to include dependencies. Right now we have to build your project and include the JAR file and all its dependencies by hand.

The version currently released to your maven repository is the very old 1.0.0 release, please upload the current version.

**Comment by sfat** [comment]
@karan can you give me temporarly commit access to the main branch so I can make the release?

**Comment by karan** [comment]
@sfat Done. Do you want to be the maintainer for this project? That would mean handling PR's, releasing updates and generally guiding the project.

**Comment by sfat** [comment]
@karan if you got other stuff on your plate, I can help as much as I can

**Comment by sfat** [comment]
@fbis251 I am going to release the new release version (1.0.1) after #105 and #104 will be closed.

**Comment by sfat** [comment]
```
<dependency>
            <groupId>com.github.jreddit</groupId>
            <artifactId>jreddit</artifactId>
            <version>1.0.2</version>
   </dependency>
```
Had a problem when I did 1.0.1 and I had to remake the release.
