### ISSUE TITLE
No Such Field Error

### ISSUE THREAD

**Issue by apythoncoder** [karan/jReddit#112]
When trying to run an app that includes the jreddit library, a no such field error gets thrown: `java.lang.NoSuchFieldError: org.apache.http.message.BasicLineFormatter.INSTANCE`

[I've posted this on SO](https://stackoverflow.com/questions/28222095/no-such-field-error-when-using-jreddit), but as there was no response, I'd thought I'd try here.

Thanks.

**Comment by sfat** [comment]
You gotta give me more info related to what you're doing. One reason of your problem would be that you have an older version of http client, given the fact ```BasicLineFormatter``` was added from 4.0.
Maybe show me your maven dependency or something to see what do you have in your classpath. 
Or how are you making use of the jReddit library. Is it through maven or you imported the jar manually?

**Comment by apythoncoder** [comment]
It's through a .jar file
![screen shot 2015-01-30 at 09 31 45](https://cloud.githubusercontent.com/assets/5155670/5973662/e198a418-a862-11e4-90ed-d3cc4d50da8f.png)

And I've added the dependencies in the build.gradle like this:
```
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:21.0.3'
    compile files('libs/jreddit-1.0.1-SNAPSHOT.jar')
    compile files('libs/json-simple-1.1.1.jar')
    compile files('libs/commons-io-2.4.jar')
    compile files('libs/httpclient-4.3.6.jar')
    compile files('libs/httpcore-4.3.3.jar')
    compile files('libs/commons-logging-1.1.3.jar')

}
```

**Comment by jacdaw** [comment]
Hi - I'm also getting this error. Has any solution been found yet?

**Comment by sfat** [comment]
hey @apythoncoder and @jacdaw. I think this is not a problem related to the jReddit itself. It seems that it's a problem related with the shipped android which comes with an outdated httpclient. You can check the question and some of the suggestions suggested by the guy that answered the question: [java.lang.NoSuchFieldError: org.apache.http.message.BasicLineFormatter.INSTANCE](https://stackoverflow.com/questions/20238421/java-lang-nosuchfielderror-org-apache-http-message-basiclineformatter-instance). Let me know if you manage to solve this problem with the second proposal (the httpclient port for android https://hc.apache.org/httpcomponents-client-4.3.x/android-port.html)

**Comment by jacdaw** [comment]
Thanks!

**Comment by sfat** [comment]
Let me know if you solve your issue and if this can be closed.

**Comment by apythoncoder** [comment]
This solved the issue for me - thanks.
