### ISSUE TITLE
HttpRestClient is incompatible with Android

### ISSUE THREAD

**Issue by ntsikerdanos** [karan/jReddit#117]
Following the discussion from here: https://www.reddit.com/r/androiddev/comments/2ygmgm/having_trouble_with_apache_httpclient_in_android/

The version of `httpclient` supplied with Android is older than the one used with jReddit (4.3.3). This causes issues when trying to use jReddit's `HttpRestClient` on Android due to missing classes that are only present in the newer version of `httpclient` (such as `RequestConfig`) and incompatibilities (such as `UrlEncodedFormEntity` on Android not being able to take a `java.nio.charset.Charset`).

The issue regarding missing classes can be solved by using [this Android port](https://hc.apache.org/httpcomponents-client-4.3.x/android-port.html) of `httpclient` 4.3 and excluding the `httpclient` dependency from jReddit. An example:

    compile('com.github.jreddit:jreddit:1.0.2') {
        exclude group: 'org.apache.httpcomponents', module: 'httpclient'
    }

    compile 'org.apache.httpcomponents:httpclient-android:4.3.5.1'

However, this brings to light the second issue. [This line](https://github.com/karan/jReddit/blob/master/src/main/java/com/github/jreddit/utils/restclient/HttpRestClient.java#L156) from `HttpRestClient` throws an exception at run time because, in Android, `UrlEncodedFormEntity` does not have a constructor that matches `List<NameValuePair>, CharSet`. (It has two constructors: one that takes `List<NameValuePair>` and one that takes `List<NameValuePair>, String`.)

    java.lang.NoSuchMethodError: org.apache.http.client.entity.UrlEncodedFormEntity.<init>
        at com.github.jreddit.utils.restclient.HttpRestClient.post(HttpRestClient.java:156)

Two possible solutions:

1. Downgrade `httpclient` in jReddit to be compatible with Android

2. Provide a separate artifact specifically for targeting Android that uses `httpclient-android` and `UrlEncodedFormEntityHC4` (and its ilk) for compatibility.

Disclaimer: I have not tested the extent of incompatibilities on Android. It's likely that there are more than just the one described here and other classes will need changed as well.

**Comment by sfat** [comment]
hey @ntsikerdanos, there were recently a couple of people that had a similar problem.  please check https://github.com/karan/jReddit/issues/112
Let me know if you need more clarification. One thing that I don't understand is why are you trying to use the old version of httpclient and not use the one specified in the android port url?

**Comment by ntsikerdanos** [comment]
#112 does look to be the same issue, though this issue was not solved by simply including the `httpclient-android` port.

Since Android ships with an older version of `httpclient`, it seems that the older version will be preferred over `httpclient-android` unless the newer classes are used explicitly (`UrlEncodedFormEntityHC4`).

So unless we use `UrlEncodedFormEntityHC4` directly, [the outdated Android version](https://android.googlesource.com/platform/external/apache-http/+/master/src/org/apache/http/client/entity/UrlEncodedFormEntity.java) will be used. As specified in the description, Android's version of `UrlEncodedFormEntity` does not have a constructor that matches what's currently used in jReddit and will throw a `NoSuchMethodError` at run time.

**Comment by ntsikerdanos** [comment]
`httpclient-android` version was a typo (should have been 4.3.5.1). It's been fixed in the description.

**Comment by sfat** [comment]
@ntsikerdanos what if we would change the 
```
UrlEncodedFormEntity entity = new UrlEncodedFormEntity(params, Consts.UTF_8);
```
to 
```
UrlEncodedFormEntity entity = new UrlEncodedFormEntity(params, "UTF-8");
```
Would that help for the error that you get?
or if you add the httpclient-android you will not have the ```UrlEncodedFormEntity``` anymore? Or is this different? https://developer.android.com/reference/org/apache/http/client/entity/UrlEncodedFormEntity.html

**Comment by ntsikerdanos** [comment]
That change would likely work in this instance (FYI there's a constant `HTTP.UTF_8`). There are two caveats to that change:

1. There might be further incompatibilities that haven't been found yet. I haven't tested much of the library myself (in fact, I don't actually use it myself, I just logged this issue on behalf of the OP from the reddit thread in the description).

2. There's nothing to enforce compatibility between jReddit and Android, so the devs would have to be careful not to introduce further issues in the future.

`httpclient-android` adds the classes that Android's `httpclient` lacks, but it also adds the updated versions of existing classes, albeit with different names. Android itself includes `UrlEncodedFormEntity`, so for compatibility's sake, `httpclient-android` adds the updated version of the class as `UrlEncodedFormEntityHC4`. See [the Compatibility notes section of this page](https://hc.apache.org/httpcomponents-client-4.3.x/android-port.html) for more info.

**Comment by sfat** [comment]
I'm finishing up a Android that does a simple login of the user and retrieves the list of submissions from a particular subreddit (I've copy pasted from the README.md). 
Gonna push it in a separate branch or directory so people will see how to set up.
In order to make the android example work, I need to release 1.0.3.

**Comment by sfat** [comment]
added an example in #123 . Closing this guy. Will do a realease shortly
