### ISSUE TITLE
Can't search the getSubmissions() method inside the project

### ISSUE THREAD

**Issue by ahsanbagwan** [karan/jReddit#118]
I was going through examples GetPaginatedTopics.java within the examples package. Here it shows there is this `getSubmissions()` method on the `Submissions` instance. 

But when I peered inside the `Submissions` class I couldn't find any method by that name. What am I missing here? If this question is very lazy I apologize.

**Comment by sfat** [comment]
@ahsanbagwan have you looked over this? https://github.com/karan/jReddit/blob/master/src/main/java/examples/SubmissionsExample.java

**Comment by ahsanbagwan** [comment]
No, I didn't. Is that the place where the new example is?

**Comment by sfat** [comment]
@ahsanbagwan yeah, that ```examples``` directory from the root of the project is deprecated, if I'm not mistaken

**Comment by sfat** [comment]
@ahsanbagwan made an update to the project to remove the top ```examples``` (was deprecated). Make sure you check the class I provided the other day. I'm gonna close this guy if there is not issue related, but thanks for making me catch this directory that needed cleanup :)
