### ISSUE TITLE
Stupid Question

### ISSUE THREAD

**Issue by TomsOverBaghdad** [karan/jReddit#124]
How do i get the home page, ive tried so many things, and cant seem to just get the main page, i can get any subreddit though :)

**Comment by TomsOverBaghdad** [comment]
this works. but is it the right way?

Submissions subms = new Submissions(mRestClient, null);
return subms.parse("/hot.json");

**Comment by captdan** [comment]
Yeah I think that's right.

**Comment by TomsOverBaghdad** [comment]
I feel like that should be more obvious in the code or for an example.

**Comment by sfat** [comment]
added an example in #125 . Let me know if it's okay.

**Comment by sfat** [comment]
can I close this guy, @TomsOverBaghdad ?
