### ISSUE TITLE
Maven build fails

### ISSUE THREAD

**Issue by DoktuhParadox** [karan/jReddit#80]
The maven build fails when running `mvn clean install`. Here are the errors: http://pastebin.com/1FFz8JnB
For release:prepare, these are the errors:
http://pastebin.com/tF2vPXLt
And of course the last build step fails as well. I recommend a switch to Gradle. `gradle build` and forget.

**Comment by sfat** [comment]
@MasterScrat check the README section, it has been updated with the maven dependency necessary for you to use in your project
