### ISSUE TITLE
Error while importing maven project into Eclipse

### ISSUE THREAD

**Issue by ahsanbagwan** [karan/jReddit#81]
I get this error while importing the maven project into eclipse:

Failure to transfer org.apache.maven.plugins:maven-enforcer-plugin:pom:1.0 from http://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced. Original error: Could not transfer artifact org.apache.maven.plugins:maven-enforcer-plugin:pom:1.0 from/to central (http://repo.maven.apache.org/maven2): null to http://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-enforcer-plugin/1.0/maven-enforcer-plugin-1.0.pom

Am I missing something trivial? Searching the error did not present any relevant results.

IDE Version: 3.8.1 
Eclipse Plugin: m2e
Platform: Ubuntu 14.04

**Comment by sfat** [comment]
@ahsanbagwan did you manage to resolve your problem? I am going to close this and you can create a separate issue if you encountered other problems.
