### ISSUE TITLE
Sorting submissions does not work

### ISSUE THREAD

**Issue by SliZeing** [karan/jReddit#92]
I just updated one of my bots to the latest version of the code, and I'm having a issue where sorting doesn't work at all. It's only returning the hot submissions, nothing else.

I took a quick look at ApiEndpointUtils.java and noticed that some of the calls to the API was not correct (e.g. On <code>SUBMISSIONS_GET</code>, <code>/r/%s.json?%s</code> should be <code>/r/%s/%s.json</code>). So I tried fixing that, but with no luck.

**Comment by sfat** [comment]
@fiyarburst I can close this, right?
