### ISSUE TITLE
Posting comments without a captcha is broken

### ISSUE THREAD

**Issue by AnteChronos** [karan/jReddit#95]
When posting a comment with no captcha, there is an issue with how the querystring is built, and later parsed, that causes an `ArrayIndexOutOfBoundsException`.

In `Messages.compose`, the querystring is constructed and passed to `HttpRestClient.post`.  If there is no captcha, the String will end up looking something like this:

`captcha=&iden=&subject=some subject....`

In `HttpRestClient.convertRequestStringToList`, the strings is then tokenized on '&', with each token being tokenized again on '='.  The final array produced is then indexed into directly.

This means that, when there is no captcha, the string is tokenized into an array whose first element is "captcha=".  When that String is then tokenized on '=', this results in an array of length 1 (the empty string to the right of the '=' is ignored by `String.split`).  So when the code reaches `nameValue[1]`, an exception is thrown, since there is no second element.

**Comment by dincciftci** [comment]
My commit includes a change to the HttpRestClient file and will probably fix this issue. See here:https://github.com/karan/jReddit/pull/105

**Comment by sfat** [comment]
@dincciftci #105 has been merged. Can I close this guy?

**Comment by dincciftci** [comment]
@sfat go ahead
